name: Build All Examples

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-examples:
    name: Build Arduino Examples for Digispark
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          fqbn: "digistump:avr:digispark-tiny"
          platforms: |
            - name: digistump:avr
              source-url: https://raw.githubusercontent.com/ArminJo/DigistumpArduino/master/package_digistump_index.json
          sketch-paths: |
            - examples
          libraries: |
            - source-path: ./src
          verbose: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
